version: "2"

services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    command: [/usr/local/bin/selenium.sh]
    volumes:
      - ./scripts:/usr/local/bin
    container_name: selenium

  server:
    image: jeremycraigmartinez/devdot
    ports:
      - "4000:4000"
    command: [/app/scripts/ci-test.sh]
    volumes:
      - ./:/app
    container_name: devdot
    depends_on:
      - "selenium"
